services:
  apache:
    container_name: apache
    build:
      context: /home/ubuntu1/tasks/task_12/configs/local/apache
      dockerfile: dockerfile
    ports:
      - 8080:8080
    networks:
      - br0
  
  nginx:
    user: nginx
    container_name: nginx
    build:
      context: /home/ubuntu1/tasks/task_12/configs/local/nginx
      dockerfile: dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - br0
    volumes:
      - /etc/ssl/self-signed:/etc/ssl/self-signed
    depends_on:
      - apache

networks:
  br0:
    driver: bridge

