FROM alpine:3.18

# Установка зависимостей
RUN apk add --no-cache \
    gcc \
    g++ \
    make \
    libc-dev \
    pcre-dev \
    zlib-dev \
    gd-dev \
    openssl-dev \
    wget \
    && wget http://nginx.org/download/nginx-1.24.0.tar.gz \
    && tar -zxvf nginx-1.24.0.tar.gz \
    && cd nginx-1.24.0 \
    && ./configure --with-http_image_filter_module --with-http_ssl_module \
    && make \
    && make install \
    && cd .. \
    && rm -rf nginx-1.24.0*

# Копируем конфигурацию Nginx
COPY ./nginx.conf /usr/local/nginx/conf/nginx.conf

# Копируем сайт
RUN mkdir -p /usr/local/nginx/html
COPY ./site /usr/local/nginx/html

# Создаем системного пользователя для Nginx
RUN adduser -S -D -H nginx && \
    chown -R nginx /usr/local/nginx /usr/local/nginx/html


# Команда запуска
ENTRYPOINT ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]
